// Demo-store builder for the App Store listing (run once, idempotent-ish).
// Creates polished demo products on the connected store with contextual
// "drag to spin" instructions (per Shopify's demo-store guidelines),
// attaches existing spins, pushes metafields, and drafts Shopify's sample
// products out of the storefront (reversible).
//
// Run: npx tsx --env-file=.env --env-file=.env.local scripts/setup-demo-store.ts

import { execFileSync } from "node:child_process";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { AwsClient } from "aws4fetch";

const prisma = new PrismaClient();

const API = "2026-01";

async function gql<T>(shop: string, token: string, query: string, variables?: object): Promise<T> {
  const res = await fetch(`https://${shop}/admin/api/${API}/graphql.json`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-Shopify-Access-Token": token },
    body: JSON.stringify({ query, variables }),
  });
  const json = (await res.json()) as { data?: T; errors?: unknown };
  if (json.errors || !json.data) throw new Error(JSON.stringify(json.errors ?? json).slice(0, 400));
  return json.data;
}

// Extract a clean poster frame from a local spin MP4 and upload it to R2 so
// Shopify can ingest it as the product image.
function extractFrame(videoPath: string, outPath: string) {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const ffmpeg = require("@ffmpeg-installer/ffmpeg").path as string;
  execFileSync(ffmpeg, ["-y", "-loglevel", "error", "-i", videoPath, "-frames:v", "1", "-q:v", "2", outPath]);
}

async function uploadToR2(localPath: string, key: string): Promise<string> {
  const client = new AwsClient({
    accessKeyId: process.env.R2_ACCESS_KEY_ID!,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
    service: "s3",
    region: "auto",
  });
  const body = readFileSync(localPath);
  const put = await client.fetch(
    `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com/${process.env.R2_BUCKET}/${key}`,
    { method: "PUT", body, headers: { "Content-Type": "image/jpeg" } },
  );
  if (!put.ok) throw new Error(`R2 PUT failed ${put.status}`);
  return `${process.env.R2_PUBLIC_URL}/${key}`;
}

const DEMO_NOTE = (product: string) =>
  `<p><strong>👇 This is a live Spinr demo — drag the 360° view below to turn the ${product} with your mouse or finger.</strong></p>` +
  `<p>The interactive spin on this page was generated by <a href="https://thespinr.com">Spinr</a> from ordinary product photos in about three minutes — no photography rig, no 3D artist, no code. Every product on this store works the same way.</p>`;

// Demo products: local spin video (for the poster frame), matched to an
// existing Spin row by the R2 video's byte size (the downloaded MP4s in
// assets/ are byte-identical to the mirrored originals).
const DEMO = [
  { title: "Leather Handbag", price: "189.00", video: "assets/Videos/bag.mp4", handleHint: "leather-handbag", noun: "bag" },
  { title: "Designer Sunglasses", price: "129.00", video: "assets/Videos/sunglasses.mp4", handleHint: "designer-sunglasses", noun: "sunglasses" },
  { title: "Yellow Slide Sandal", price: "59.00", video: "assets/Videos/yellow sandle.mp4", handleHint: "yellow-slide-sandal", noun: "sandal" },
];

const SAMPLE_TITLES = [
  "Gift Card",
  "Selling Plans Ski Wax",
  "The 3p Fulfilled Snowboard",
  "The Archived Snowboard",
  "The Collection Snowboard: Hydrogen",
  "The Collection Snowboard: Liquid",
  "The Collection Snowboard: Oxygen",
  "The Compare at Price Snowboard",
  "The Complete Snowboard",
  "The Hidden Snowboard",
  "The Inventory Not Tracked Snowboard",
  "The Minimal Snowboard",
  "The Multi-location Snowboard",
  "The Multi-managed Snowboard",
  "The Out of Stock Snowboard",
  "The Videographer Snowboard",
];

async function main() {
  const conn = await prisma.shopifyConnection.findFirst({
    where: { shop: { contains: "kokok" } },
  });
  if (!conn) throw new Error("kokok connection not found");
  const { shop, accessToken: token } = conn;
  console.log("store:", shop);

  // Map spin rows by their mirrored video size for matching.
  const readySpins = await prisma.spin.findMany({
    where: { status: "ready", videoUrl: { not: null }, shopifyProductGid: null },
    select: { id: true, title: true, videoUrl: true },
  });
  const sizeToSpin = new Map<number, { id: string; title: string }>();
  for (const s of readySpins) {
    const head = await fetch(s.videoUrl!, { method: "HEAD" });
    const len = Number(head.headers.get("content-length") ?? 0);
    if (len) sizeToSpin.set(len, { id: s.id, title: s.title });
  }

  const tmp = mkdtempSync(join(tmpdir(), "spinr-demo-"));
  const productUrls: string[] = [];

  for (const d of DEMO) {
    const stat = readFileSync(d.video);
    const spin = sizeToSpin.get(stat.byteLength);
    console.log(`\n${d.title}: spin match = ${spin ? `${spin.id} (${spin.title})` : "NONE — will create product without spin"}`);

    // Poster frame → R2
    const framePath = join(tmp, `${d.handleHint}.jpg`);
    extractFrame(d.video, framePath);
    const imageUrl = await uploadToR2(framePath, `demo/${d.handleHint}.jpg`);

    // Create (or reuse) the product
    const existing = await gql<{ products: { edges: Array<{ node: { id: string; handle: string } }> } }>(
      shop, token,
      `query($q: String!) { products(first: 1, query: $q) { edges { node { id handle } } } }`,
      { q: `title:'${d.title}'` },
    );
    let gid: string;
    let handle: string;
    if (existing.products.edges[0]) {
      ({ id: gid, handle } = existing.products.edges[0].node);
      console.log("  product exists:", handle);
    } else {
      const created = await gql<{
        productSet: { product: { id: string; handle: string } | null; userErrors: Array<{ message: string }> };
      }>(
        shop, token,
        `mutation($input: ProductSetInput!) {
          productSet(input: $input, synchronous: true) {
            product { id handle }
            userErrors { message }
          }
        }`,
        {
          input: {
            title: d.title,
            descriptionHtml: DEMO_NOTE(d.noun),
            status: "ACTIVE",
            files: [{ originalSource: imageUrl, contentType: "IMAGE" }],
            productOptions: [{ name: "Title", values: [{ name: "Default Title" }] }],
            variants: [{ price: d.price, optionValues: [{ optionName: "Title", name: "Default Title" }] }],
          },
        },
      );
      if (!created.productSet.product) throw new Error(JSON.stringify(created.productSet.userErrors));
      ({ id: gid, handle } = created.productSet.product);
      console.log("  created:", handle);
    }

    // Attach + push the spin
    if (spin) {
      await prisma.spin.update({
        where: { id: spin.id },
        data: { shopifyProductGid: gid, shopifyProductHandle: handle, title: d.title, pushedToShopifyAt: new Date() },
      });
      await gql(shop, token,
        `mutation($m: [MetafieldsSetInput!]!) { metafieldsSet(metafields: $m) { userErrors { message } } }`,
        { m: [{ ownerId: gid, namespace: "custom", key: "spinr_id", type: "single_line_text_field", value: spin.id }] },
      );
      console.log("  spin attached + pushed");
    }
    productUrls.push(`https://${shop}/products/${handle}`);
  }

  // Polish the existing chair demo product
  const chair = await gql<{ products: { edges: Array<{ node: { id: string; handle: string } }> } }>(
    shop, token, `query { products(first: 1, query: "title:'chair'") { edges { node { id handle } } } }`,
  );
  if (chair.products.edges[0]) {
    const { id, handle } = chair.products.edges[0].node;
    await gql(shop, token,
      `mutation($input: ProductUpdateInput!) { productUpdate(product: $input) { userErrors { message } } }`,
      { input: { id, title: "Retro Leather Office Chair", descriptionHtml: DEMO_NOTE("chair") } },
    );
    console.log("\nchair product polished");
    productUrls.push(`https://${shop}/products/${handle}`);
  }

  // Draft the sample products (reversible: set back to ACTIVE to restore)
  for (const title of SAMPLE_TITLES) {
    const found = await gql<{ products: { edges: Array<{ node: { id: string } }> } }>(
      shop, token, `query($q: String!) { products(first: 1, query: $q) { edges { node { id } } } }`,
      { q: `title:'${title.replace(/'/g, "\\'")}'` },
    );
    const node = found.products.edges[0]?.node;
    if (node) {
      await gql(shop, token,
        `mutation($input: ProductUpdateInput!) { productUpdate(product: $input) { userErrors { message } } }`,
        { input: { id: node.id, status: "DRAFT" } },
      );
      console.log("drafted sample:", title);
    }
  }

  rmSync(tmp, { recursive: true, force: true });
  console.log("\nDemo product URLs:");
  for (const u of productUrls) console.log(" -", u);
}

main().finally(() => prisma.$disconnect());
